const endpoints = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  VERIFY_OTP: "/auth/verify-otp",
  VERIFY_CHANGE_EMAIL: "/auth/verify-otp-and-change-email",
  RESEND_OTP: "/auth/resend-otp",
  CHANGE_EMAIL: "/auth/change-email",
  RESET_PASSWORD: "/auth/forgot-password/reset",
  FORGOT_PASSWORD: "/auth/forgot-password",
  VERIFY_OTP_FORGOT_PASSWORD: "/auth/forgot-password/verify",
  SHIPPING_ADDRESS: "/shipping-address",
  DEFAULT_SHIPPING_ADDRESS: "/shipping-address/default",
  CHANGE_PASSWORD: "/auth/change-password",
  CUSTOMER_PROFILE: "/customer",
  UPLOAD_AVATAR: "/customer/avatar",
  PURCHASE_REQUEST: "/purchase-request",
  WITH_LINK_PURCHASE_REQUEST: "/purchase-request/online-request",
  WITHOUT_LINK_PURCHASE_REQUEST: "/purchase-request/offline-request",
  CHECKING_PURCHASE_REQUEST: "/purchase-request/checking",
  WALLET: "/wallet",
  TRANSACTION_HISTORY: "/transactions/current-user",
  QUOTATION: "/quotation",
  REJECT_QUOTATION: "/quotation/reject",
  QUOTATION_CALCULATE: "/quotation/calculate",
  CREATE_SUB_REQUEST: "/purchase-request/create-sub-request",
  SUB_REQUEST: "/sub-request",
  RAW_DATA: "/ai/get-raw-data",
  CHECKOUT: "/orders/checkout",
  ORDER: "/orders",
  UPDATE_SHIPPING: "/orders/update-shipping",
  CANCEL_ORDER: "/orders/cancel",
  HS_CODES: "/hs-code/search",
  DIRECT_CHECKOUT: "/orders/direct-checkout",
  FEEDBACK: "/feedback",
  REFUND: "/refund-ticket",
  // CHECKPAYMENT: '/wallet/check-payment-vnpay',
};
export default endpoints;
