export const SHIPMENT_TYPE = [
  { type: "FedEx International Priority® Express", value: "dịch vụ giao hàng nhanh, ưu tiên, tận nơi (door-to-door) cho các thị trường chọn lọc tại châu Á, Hoa Kỳ, Canada và châu Âu, với thời gian giao hàng thường trong 1-2 ngày làm việc" },
  { type: "FedEx International First®", value: "dịch vụ chuyển phát nhanh quốc tế ưu tiên, đảm bảo thời gian giao hàng và thông quan, giao hàng tận nơi với cam kết giao hàng vào buổi sáng sớm cho các lô hàng < 68kg mỗi kiện" },
  { type: "FedEx International Priority®", value: "dịch vụ vận chuyển quốc tế nhanh chóng của FedEx, hướng đến việc giao hàng trong thời gian ngắn (thường là 1-3 ngày làm việc) đến nhiều quốc gia và vùng lãnh thổ trên thế giới" },
  { type: "FedEx International Economy®", value: "dịch vụ giao hàng quốc tế tiết kiệm chi phí của FedEx, phù hợp với những lô hàng không quá gấp nhưng vẫn cần độ tin cậy cao và thông quan hải quan đầy đủ." },
  { type: "FedEx International Ground® and FedEx Domestic Ground®", value: "FedEx International Ground® and FedEx Domestic Ground®" },
  { type: "FedEx First Overnight®", value: "FedEx First Overnight®" },
  { type: "FedEx First Overnight® Freight", value: "FedEx First Overnight® Freight" },
  { type: "FedEx 1Day® Freight (Hawaii service is to and from the island of Oahu only)", value: "FedEx 1Day® Freight (Hawaii service is to and from the island of Oahu only)" },
  { type: "FedEx 2Day® Freight (Hawaii service is to and from the island of Oahu only)", value: "FedEx 2Day® Freight (Hawaii service is to and from the island of Oahu only)" },
  { type: "FedEx 3Day® Freight (Except Alaska and Hawaii)", value: "FedEx 3Day® Freight (Except Alaska and Hawaii)" },
  { type: "FedEx International Priority® Freight", value: "FedEx International Priority® Freight" },
  { type: "FedEx International Economy® Freight", value: "FedEx International Economy® Freight" },
  { type: "FedEx® International Deferred Freight", value: "FedEx® International Deferred Freight" },
  { type: "FedEx International Priority DirectDistribution®", value: "FedEx International Priority DirectDistribution®" },
  { type: "FedEx International Priority DirectDistribution® Freight", value: "FedEx International Priority DirectDistribution® Freight" },
  { type: "International Ground® Distribution (IGD)", value: "International Ground® Distribution (IGD)" },
  { type: "FedEx Home Delivery®", value: "FedEx Home Delivery®" },
  { type: "FedEx Ground® Economy (Formerly known as FedEx SmartPost®)", value: "FedEx Ground® Economy (Formerly known as FedEx SmartPost®)" },
  { type: "FedEx Priority Overnight®", value: "FedEx Priority Overnight®" },
  { type: "FedEx Standard Overnight® (Hawaii outbound only)", value: "FedEx Standard Overnight® (Hawaii outbound only)" },
  { type: "FedEx 2Day®", value: "FedEx 2Day®" },
  { type: "FedEx 2Day® AM (Hawaii outbound only)", value: "FedEx 2Day® AM (Hawaii outbound only)" },
  { type: "FedEx Express Saver® (Except Alaska and Hawaii)", value: "FedEx Express Saver® (Except Alaska and Hawaii)" },
  { type: "FedEx SameDay®", value: "FedEx SameDay®" },
  { type: "FedEx SameDay® City (Selected U.S. Metro Areas)", value: "FedEx SameDay® City (Selected U.S. Metro Areas)" },
]