name: Deploy FE to VPS on main push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and deploy FE
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/GlobalShopper_FrontEnd || git clone https://github.com/Global_Shopper/GlobalShopper_FrontEnd.git && cd GlobalShopper_FrontEnd  
            git checkout main
            git pull origin main

            docker stop globalshopperfe || true
            docker rm globalshopperfe || true
            docker rmi globalshopperfe || true

            docker build -t globalshopperfe .
            docker run -d --name globalshopperfe -p 3000:80 globalshopperfe